apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306  
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"  
        - name: MYSQL_DATABASE
          value: "testdb"  
        - name: MYSQL_USER
          value: "user"  
        - name: MYSQL_PASSWORD
          value: "password" 
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
