---
- name: Setup k0s Cluster
  hosts: k0s
  become: true
  vars:
    cilium_version: "1.16.3"
    hubble_version: "1.16.2"

  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
          - sudo
          - kubectl
          - conntrack
        state: present
        update_cache: true

    - name: Install k0s on the controller
      when: inventory_hostname in groups['k0s_controller']
      shell: |
        curl -sSLf https://get.k0s.sh | sudo sh
        sudo k0s install controller
        sudo k0s start

    - name: Wait for k0s controller to be running
      when: inventory_hostname in groups['k0s_controller']
      command: sudo k0s status
      register: k0s_status
      until: "'running' in k0s_status.stdout"
      retries: 10
      delay: 5

    - name: Install k0s on the worker
      when: inventory_hostname in groups['k0s_worker']
      shell: |
        curl -sSLf https://get.k0s.sh | sudo sh
        sudo k0s install worker --token-file /tmp/k0s_worker_token
        sudo k0s start

    - name: Wait for k0s worker to be running
      when: inventory_hostname in groups['k0s_worker']
      command: sudo k0s status
      register: k0s_worker_status
      until: "'running' in k0s_worker_status.stdout"
      retries: 10
      delay: 5

    - name: Install Cilium
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/{{ cilium_version }}/install/kubernetes/quick-install.yaml
      register: cilium_install
      until: cilium_install.rc == 0
      retries: 3
      delay: 5

    - name: Wait for Cilium to be ready
      command: kubectl wait --for=condition=available --timeout=60s deployment/cilium -n kube-system
      register: cilium_ready
      until: cilium_ready.rc == 0
      retries: 3
      delay: 5

    - name: Install Hubble
      shell: |
        curl -sL https://raw.githubusercontent.com/cilium/hubble/{{ hubble_version }}/install/hubble.yaml | kubectl apply -f -
      register: hubble_install
      until: hubble_install.rc == 0
      retries: 3
      delay: 5

    - name: Wait for Hubble to be available
      command: kubectl wait --for=condition=available --timeout=60s deployment/hubble-ui -n kube-system

    - name: Install Grafana
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/grafana/helm-charts/main/charts/grafana/templates/deployment.yaml
      register: grafana_install
      until: grafana_install.rc == 0
      retries: 3
      delay: 5

    - name: Deploy MySQL
      kubernetes.core.k8s:
        state: present
        src: roles/mysql.yaml
        namespace: default

    - name: Deploy User Service
      kubernetes.core.k8s:
        state: present
        src: roles/user-service.yaml
        namespace: default

    - name: Deploy Unauthorized Pod
      kubernetes.core.k8s:
        state: present
        src: roles/unauthorized-pod.yaml
        namespace: default

    - name: Create Cilium Network Policies
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: networking.cilium.io/v2
        kind: NetworkPolicy
        metadata:
          name: allow-user-to-mysql
        spec:
          endpointSelector:
            matchLabels:
              app: user-service
          ingress:
            - fromEndpoints:
                - matchLabels:
                    app: mysql
        EOF

    - name: Create Unauthorized Pod Policy
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: networking.cilium.io/v2
        kind: NetworkPolicy
        metadata:
          name: deny-unauthorized
        spec:
          endpointSelector:
            matchLabels:
              app: unauthorized-pod
          ingress:
            - fromEndpoints: []
        EOF
