version: '3.8'

services:
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user 
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
